name: actions

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
jobs:   
  test:    
    runs-on: ubuntu-latest

    steps: 
      - uses: action/checkout@v1
      - name: Uses Node.js ${{matrix.node-version}}
        uses: action/steps-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install
        run: npm Install
      - name: test
        run: npm test
  